# Generated by Django 4.2.16 on 2024-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_alter_comment_options_comment_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentaire',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_flagged',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(max_length=100),
        ),
    ]
