# Generated by Django 4.2.16 on 2024-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_rename_commentaire_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commentaire',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(max_length=200),
        ),
    ]
