# Generated by Django 4.2.16 on 2024-12-05 05:52

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commentaire',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(max_length=200),
        ),
    ]
