# Generated by Django 4.2.16 on 2024-12-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0011_rename_userprofile_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
