# Generated by Django 5.1.5 on 2025-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0014_remove_reply_comment_remove_reply_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Vidéo")],
                default="image",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="blogs",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="posts/videos/"),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
