# Generated by Django 5.1.5 on 2025-09-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0016_comment_liked_by_comment_likes_delete_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date_added"]},
        ),
    ]
